/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.BookingDAOImpl;
import dao.CustomerDAOImpl;
import dao.RoomDAOImpl;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Booking;
import model.Customer;
import model.Room;
import util.DateUtils;

/**
 *
 * @author Ahme_vn75
 */
public class JFrameNewBooking extends javax.swing.JFrame {
    
    BookingDAOImpl bookingDAO = new BookingDAOImpl();
    RoomDAOImpl roomDAO = new RoomDAOImpl();
   
    
    
    public JFrameNewBooking() {
        initComponents();
        setRoomTable();
        checkGenderRadioButton();
        checkNationalityRadioButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFielEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jDateCheckIn = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jDateCheckOut = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonAze = new javax.swing.JRadioButton();
        jRadioButtonTur = new javax.swing.JRadioButton();
        jRadioButtonRus = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldPhoneNumber = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxAddress = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jDateChooserDob = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRoom = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTotalCoast2 = new javax.swing.JTextField();
        jButtonCreateBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));

        jPanel6.setBackground(new java.awt.Color(58, 120, 145));

        jPanel4.setBackground(new java.awt.Color(61, 82, 91));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(148, 215, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(220, 41, 65))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(184, 215, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("First name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 28, 188, -1));

        jTextFieldFirstName.setBackground(new java.awt.Color(101, 241, 195));
        jPanel1.add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 48, 180, -1));

        jLabel3.setText("Last name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 79, -1, -1));

        jTextFieldLastName.setBackground(new java.awt.Color(101, 241, 195));
        jPanel1.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 99, 180, -1));

        jLabel4.setText("E-Mail");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 130, -1, -1));

        jTextFielEmail.setBackground(new java.awt.Color(101, 241, 195));
        jPanel1.add(jTextFielEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 150, 180, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 210, 200));

        jPanel2.setBackground(new java.awt.Color(148, 215, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(220, 41, 65))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Check In");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel2.add(jDateCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, -1));

        jLabel9.setText("Check Out");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel2.add(jDateCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 190, 140));

        jPanel3.setBackground(new java.awt.Color(148, 215, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nationality", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(220, 41, 65))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButtonAze.setBackground(new java.awt.Color(101, 241, 195));
        jRadioButtonAze.setText("Azerbaijani");
        jPanel3.add(jRadioButtonAze, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 166, -1));

        jRadioButtonTur.setBackground(new java.awt.Color(101, 241, 195));
        jRadioButtonTur.setText("Turkish");
        jRadioButtonTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTurActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButtonTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 166, -1));

        jRadioButtonRus.setBackground(new java.awt.Color(101, 241, 195));
        jRadioButtonRus.setText("Russian");
        jPanel3.add(jRadioButtonRus, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, 166, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 210, 120));

        jPanel5.setBackground(new java.awt.Color(148, 215, 80));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(220, 41, 65))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Phone number:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 28, 188, -1));

        jFormattedTextFieldPhoneNumber.setBackground(new java.awt.Color(101, 241, 195));
        try {
            jFormattedTextFieldPhoneNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(jFormattedTextFieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 48, 170, -1));

        jLabel6.setText("Address:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 79, -1, -1));

        jComboBoxAddress.setBackground(new java.awt.Color(101, 241, 195));
        jComboBoxAddress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baku", "Sumqayit", "Gence", "Mingechevir", "Sheki", "Qazax", "Berde" }));
        jPanel5.add(jComboBoxAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 99, 170, -1));

        jLabel7.setText("Dat of birth");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 130, -1, -1));
        jPanel5.add(jDateChooserDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 150, 170, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 200, 190));

        jPanel9.setBackground(new java.awt.Color(148, 215, 80));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(220, 41, 65))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButtonMale.setBackground(new java.awt.Color(101, 241, 195));
        jRadioButtonMale.setText("Male");
        jPanel9.add(jRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 166, -1));

        jRadioButtonFemale.setBackground(new java.awt.Color(101, 241, 195));
        jRadioButtonFemale.setText("Female");
        jPanel9.add(jRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 166, -1));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 190, 90));

        jTableRoom.setBackground(new java.awt.Color(230, 236, 239));
        jTableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRoom);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 440, 270));

        jPanel11.setBackground(new java.awt.Color(148, 215, 80));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Cost", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(220, 41, 65))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Total Cost");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jTextFieldTotalCoast2.setBackground(new java.awt.Color(101, 241, 195));
        jPanel11.add(jTextFieldTotalCoast2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, -1));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 190, 90));

        jButtonCreateBooking.setBackground(new java.awt.Color(12, 231, 245));
        jButtonCreateBooking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCreateBooking.setText("Create Booking");
        jButtonCreateBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateBookingActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonCreateBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 250, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTurActionPerformed

    private void jButtonCreateBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateBookingActionPerformed
        String name = jTextFieldFirstName.getText();
        String surname = jTextFieldLastName.getText();
        String email = jTextFielEmail.getText();

        String gender = checkGenderRadioButton();
        String nationality = checkNationalityRadioButton();

        String phone = jFormattedTextFieldPhoneNumber.getText();
        String address = (String) jComboBoxAddress.getSelectedItem();

        LocalDate dateTime = DateUtils.asLocalDate(jDateChooserDob.getDate());
        Customer newCus = new Customer(name, surname, dateTime, gender, address, phone, email, nationality);
        
        LocalDate checkIn = DateUtils.asLocalDate(jDateCheckIn.getDate());
        
        LocalDate checkOut = DateUtils.asLocalDate(jDateCheckOut.getDate());
        
        Integer id = (Integer) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 0);
        Room r = new Room();
        r.setId(id);
        Booking booking = new Booking(checkIn, checkOut, r, newCus);
        
        
       /* boolean result = bookingDAO.createBooking(booking);
        if (result) {
            JOptionPane.showMessageDialog(this, "Booking Create Success data...", "Create", JOptionPane.INFORMATION_MESSAGE);
            JFrameReseptionPanel rp = new JFrameReseptionPanel();
            rp.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Booking Create Error data...", "Error", JOptionPane.ERROR_MESSAGE);
        }*/
       
        System.out.println(name);
        System.out.println(surname);
        System.out.println(email);
        System.out.println(gender);
        System.out.println(nationality);
        System.out.println(phone);
        System.out.println(address);
        //System.out.println(date);
        System.out.println(checkIn);
        System.out.println(checkOut);
        System.out.println(id);
        
    }//GEN-LAST:event_jButtonCreateBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNewBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateBooking;
    private javax.swing.JComboBox<String> jComboBoxAddress;
    private com.toedter.calendar.JDateChooser jDateCheckIn;
    private com.toedter.calendar.JDateChooser jDateCheckOut;
    private com.toedter.calendar.JDateChooser jDateChooserDob;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNumber;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonAze;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonRus;
    private javax.swing.JRadioButton jRadioButtonTur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRoom;
    private javax.swing.JTextField jTextFielEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldTotalCoast2;
    // End of variables declaration//GEN-END:variables

    private String checkGenderRadioButton() {
        ButtonGroup bgGender = new ButtonGroup();
        bgGender.add(jRadioButtonMale);
        bgGender.add(jRadioButtonFemale);
        
        for (Enumeration<AbstractButton> buttons = bgGender.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    private String checkNationalityRadioButton() {
        ButtonGroup bgGender = new ButtonGroup();
        bgGender.add(jRadioButtonAze);
        bgGender.add(jRadioButtonRus);
        bgGender.add(jRadioButtonTur);
        
        for (Enumeration<AbstractButton> buttons = bgGender.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    private void setRoomTable() {
        List<Room> rooms = roomDAO.getAllRoom();
        
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        dtm.addColumn("ID");
        dtm.addColumn("Property");
        dtm.addColumn("Type");
        dtm.addColumn("View");
        dtm.addColumn("Adult no");
        dtm.addColumn("Child no");
        dtm.addColumn("Number");
        dtm.addColumn("Status");
        
        for(Room item : rooms){
            dtm.addRow(new Object[]{item.getId(), item.getProperty(), item.getType(), item.getView(), 
            item.getAdultNo(), item.getChildNo(), item.getNumber(), item.isStatus()});
        }
        
        jTableRoom.setModel(dtm);
    }
    
    /*private void selectedRoomTable() {
        jTableRoom.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                //jTextCustomerId.setText();
            }
            
        });
    }*/

    private Room getSelectedRoomId() {
        Room room = null;
        jTableRoom.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                Integer id = (Integer) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 0);
                String property = (String) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 1);
                String type = (String) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 2);
                String view = (String) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 4);
                int adultNo = (int) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 5);
                int childNo = (int) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 6);
                int number = (int) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 7);
                boolean status = (boolean) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 8);
                //room = new Room(id, property, type, view, adultNo, childNo, number, status);
            }
        });
        return room;
    }

    
}
