/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ahmedov
 */
public class JFrameAdminController extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAdminController
     */
    public JFrameAdminController() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonRoom = new javax.swing.JButton();
        jButtonBooking = new javax.swing.JButton();
        jButtonCustomer = new javax.swing.JButton();
        jButtonWorker = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelRoom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRoom = new javax.swing.JTable();
        jPanelBooking = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelCustomer = new javax.swing.JPanel();
        jPanelWorker = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(253, 3, 128));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(28, 17, 20));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(56, 104, 119));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmedov\\Desktop\\hotel-management-swing\\hotel-management-swing\\image\\exit.png")); // NOI18N
        jButtonExit.setText("      EXIT");
        jButtonExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        sidepanel.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 240, 60));

        jButtonRoom.setBackground(new java.awt.Color(56, 104, 119));
        jButtonRoom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRoom.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmedov\\Desktop\\hotel-management-swing\\hotel-management-swing\\image\\room_icon.png")); // NOI18N
        jButtonRoom.setText("   Room");
        jButtonRoom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRoom.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoomActionPerformed(evt);
            }
        });
        sidepanel.add(jButtonRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 60));

        jButtonBooking.setBackground(new java.awt.Color(56, 104, 119));
        jButtonBooking.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonBooking.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmedov\\Desktop\\hotel-management-swing\\hotel-management-swing\\image\\booking_icon.png")); // NOI18N
        jButtonBooking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBooking.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonBooking.setLabel("   Booking");
        jButtonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookingActionPerformed(evt);
            }
        });
        sidepanel.add(jButtonBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 60));

        jButtonCustomer.setBackground(new java.awt.Color(56, 104, 119));
        jButtonCustomer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCustomer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmedov\\Desktop\\hotel-management-swing\\hotel-management-swing\\image\\customer.png")); // NOI18N
        jButtonCustomer.setText("   Customer");
        jButtonCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        sidepanel.add(jButtonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 240, 60));

        jButtonWorker.setBackground(new java.awt.Color(56, 104, 119));
        jButtonWorker.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonWorker.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmedov\\Desktop\\hotel-management-swing\\hotel-management-swing\\image\\worker_icon.png")); // NOI18N
        jButtonWorker.setText("   Worker");
        jButtonWorker.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonWorker.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        sidepanel.add(jButtonWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 60));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jPanel3.setBackground(new java.awt.Color(56, 141, 173));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRoom.setBackground(new java.awt.Color(56, 141, 173));

        jTableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRoom);

        javax.swing.GroupLayout jPanelRoomLayout = new javax.swing.GroupLayout(jPanelRoom);
        jPanelRoom.setLayout(jPanelRoomLayout);
        jPanelRoomLayout.setHorizontalGroup(
            jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRoomLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanelRoomLayout.setVerticalGroup(
            jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 820, 450));

        jPanelBooking.setBackground(new java.awt.Color(56, 141, 173));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelBookingLayout = new javax.swing.GroupLayout(jPanelBooking);
        jPanelBooking.setLayout(jPanelBookingLayout);
        jPanelBookingLayout.setHorizontalGroup(
            jPanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBookingLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanelBookingLayout.setVerticalGroup(
            jPanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookingLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 820, 450));

        jPanelCustomer.setBackground(new java.awt.Color(56, 141, 173));

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel3.add(jPanelCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 820, 450));

        jPanelWorker.setBackground(new java.awt.Color(56, 141, 173));

        javax.swing.GroupLayout jPanelWorkerLayout = new javax.swing.GroupLayout(jPanelWorker);
        jPanelWorker.setLayout(jPanelWorkerLayout);
        jPanelWorkerLayout.setHorizontalGroup(
            jPanelWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanelWorkerLayout.setVerticalGroup(
            jPanelWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel3.add(jPanelWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 820, 450));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 810, 450));

        jPanel1.setBackground(new java.awt.Color(3, 185, 253));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Hotel Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 810, 90));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomActionPerformed
        // TODO add your handling code here:
        jPanelRoom.setVisible(true);
        jPanelBooking.setVisible(false);
    }//GEN-LAST:event_jButtonRoomActionPerformed

    private void jButtonBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookingActionPerformed
        // TODO add your handling code here:
        jPanelBooking.setVisible(true);
        jPanelRoom.setVisible(false);

    }//GEN-LAST:event_jButtonBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdminController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButtonBooking;
    private javax.swing.JButton jButtonCustomer;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRoom;
    private javax.swing.JButton jButtonWorker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBooking;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelRoom;
    private javax.swing.JPanel jPanelWorker;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableRoom;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
