/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.BookingDAOImpl;
import dao.CustomerDAOImpl;
import dao.RoomDAOImpl;
import dao.WorkerDAOImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Booking;
import model.Customer;
import model.Room;
import model.Worker;

/**
 *
 * @author Ahmedov
 */
public class JFrameAdminController extends javax.swing.JFrame {
    
    RoomDAOImpl roomDAO = new RoomDAOImpl();
    BookingDAOImpl bookingDAO = new BookingDAOImpl();
    WorkerDAOImpl workerDAO = new WorkerDAOImpl();
    CustomerDAOImpl customerDAO = new CustomerDAOImpl();
    
    DefaultTableModel dtmCustom;

    /**
     * Creates new form JFrameAdminController
     */
    public JFrameAdminController() {
        initComponents();
        getPanelRoom();
        setRoomTable();
        selectRoomTableRow();
        selectBookingTableRow();
        selectWorkerTableRow();
        selectCustomerTableRow();
        buttonEnable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonRoom = new javax.swing.JButton();
        jButtonBooking = new javax.swing.JButton();
        jButtonCustomer = new javax.swing.JButton();
        jButtonWorker = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelBooking = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBooking = new javax.swing.JTable();
        jTextFieldBookingSearch = new javax.swing.JTextField();
        jButtonBookingRemove = new javax.swing.JButton();
        jButtonBookingEdit = new javax.swing.JButton();
        jButtonBookingCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelCustomer = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButtonCustomerRemove = new javax.swing.JButton();
        jButtonCustomerEdit = new javax.swing.JButton();
        jButtonCustomerCreate = new javax.swing.JButton();
        jTextFieldFilterCustomer = new javax.swing.JTextField();
        jPanelWorker = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableWorker = new javax.swing.JTable();
        jTextFieldWorkerSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonWorkerRemove = new javax.swing.JButton();
        jButtonWorkerEdit = new javax.swing.JButton();
        jButtonWorkerCreate = new javax.swing.JButton();
        jPanelRoom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRoom = new javax.swing.JTable();
        jButtonRoomEdit = new javax.swing.JButton();
        jButtonRoomCreate = new javax.swing.JButton();
        jButtonRoomRemove = new javax.swing.JButton();
        jTextFieldRoomSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(253, 3, 128));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(28, 17, 20));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(56, 104, 119));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonExit.setText("      EXIT");
        jButtonExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        sidepanel.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 240, 60));

        jButtonRoom.setBackground(new java.awt.Color(56, 104, 119));
        jButtonRoom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRoom.setText("   ROOM");
        jButtonRoom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRoom.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoomActionPerformed(evt);
            }
        });
        sidepanel.add(jButtonRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 60));

        jButtonBooking.setBackground(new java.awt.Color(56, 104, 119));
        jButtonBooking.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonBooking.setText("   BOOKING");
        jButtonBooking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBooking.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookingActionPerformed(evt);
            }
        });
        sidepanel.add(jButtonBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 60));

        jButtonCustomer.setBackground(new java.awt.Color(56, 104, 119));
        jButtonCustomer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCustomer.setText("   CUSTOMER");
        jButtonCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerActionPerformed(evt);
            }
        });
        sidepanel.add(jButtonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 240, 60));

        jButtonWorker.setBackground(new java.awt.Color(56, 104, 119));
        jButtonWorker.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonWorker.setText("   Worker");
        jButtonWorker.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonWorker.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerActionPerformed(evt);
            }
        });
        sidepanel.add(jButtonWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 60));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jPanel3.setBackground(new java.awt.Color(56, 141, 173));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBooking.setBackground(new java.awt.Color(56, 141, 173));

        jTableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableBooking);

        jTextFieldBookingSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBookingSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBookingSearch.setText("ROOM SEARCH");
        jTextFieldBookingSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButtonBookingRemove.setBackground(new java.awt.Color(54, 224, 203));
        jButtonBookingRemove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBookingRemove.setText("Remove");

        jButtonBookingEdit.setBackground(new java.awt.Color(54, 224, 203));
        jButtonBookingEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBookingEdit.setText("Edit");

        jButtonBookingCreate.setBackground(new java.awt.Color(54, 224, 203));
        jButtonBookingCreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBookingCreate.setText("Create");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Booking Controller");

        javax.swing.GroupLayout jPanelBookingLayout = new javax.swing.GroupLayout(jPanelBooking);
        jPanelBooking.setLayout(jPanelBookingLayout);
        jPanelBookingLayout.setHorizontalGroup(
            jPanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookingLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBookingLayout.createSequentialGroup()
                        .addComponent(jButtonBookingRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonBookingEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButtonBookingCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBookingLayout.createSequentialGroup()
                        .addGroup(jPanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBookingSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
            .addGroup(jPanelBookingLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBookingLayout.setVerticalGroup(
            jPanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jTextFieldBookingSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBookingEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBookingCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBookingRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanelBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 820, 450));

        jPanelCustomer.setBackground(new java.awt.Color(56, 141, 173));

        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableCustomer);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Customer Controller");

        jButtonCustomerRemove.setBackground(new java.awt.Color(103, 224, 54));
        jButtonCustomerRemove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerRemove.setText("Remove");

        jButtonCustomerEdit.setBackground(new java.awt.Color(103, 224, 54));
        jButtonCustomerEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerEdit.setText("Edit");
        jButtonCustomerEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerEditActionPerformed(evt);
            }
        });

        jButtonCustomerCreate.setBackground(new java.awt.Color(103, 224, 54));
        jButtonCustomerCreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerCreate.setText("Create");
        jButtonCustomerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerCreateActionPerformed(evt);
            }
        });

        jTextFieldFilterCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFilterCustomerKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomerLayout.createSequentialGroup()
                        .addComponent(jButtonCustomerRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonCustomerEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButtonCustomerCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomerLayout.createSequentialGroup()
                        .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFilterCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldFilterCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCustomerEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanelCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 820, 450));

        jPanelWorker.setBackground(new java.awt.Color(56, 141, 173));

        jTableWorker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableWorker);

        jTextFieldWorkerSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldWorkerSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldWorkerSearch.setText("Customer SEARCH");
        jTextFieldWorkerSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Worker Controller");

        jButtonWorkerRemove.setBackground(new java.awt.Color(216, 224, 54));
        jButtonWorkerRemove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonWorkerRemove.setText("Remove");
        jButtonWorkerRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerRemoveActionPerformed(evt);
            }
        });

        jButtonWorkerEdit.setBackground(new java.awt.Color(216, 224, 54));
        jButtonWorkerEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonWorkerEdit.setText("Edit");

        jButtonWorkerCreate.setBackground(new java.awt.Color(216, 224, 54));
        jButtonWorkerCreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonWorkerCreate.setText("Create");
        jButtonWorkerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelWorkerLayout = new javax.swing.GroupLayout(jPanelWorker);
        jPanelWorker.setLayout(jPanelWorkerLayout);
        jPanelWorkerLayout.setHorizontalGroup(
            jPanelWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWorkerLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanelWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWorkerLayout.createSequentialGroup()
                        .addComponent(jButtonWorkerRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonWorkerEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButtonWorkerCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWorkerLayout.createSequentialGroup()
                        .addGroup(jPanelWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldWorkerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
            .addGroup(jPanelWorkerLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelWorkerLayout.setVerticalGroup(
            jPanelWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWorkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jTextFieldWorkerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWorkerEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWorkerCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWorkerRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanelWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 820, 450));

        jPanelRoom.setBackground(new java.awt.Color(56, 141, 173));

        jTableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRoom);

        jButtonRoomEdit.setBackground(new java.awt.Color(95, 102, 205));
        jButtonRoomEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRoomEdit.setText("Edit");

        jButtonRoomCreate.setBackground(new java.awt.Color(95, 102, 205));
        jButtonRoomCreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRoomCreate.setText("Create");

        jButtonRoomRemove.setBackground(new java.awt.Color(95, 102, 205));
        jButtonRoomRemove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRoomRemove.setText("Remove");
        jButtonRoomRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoomRemoveActionPerformed(evt);
            }
        });

        jTextFieldRoomSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldRoomSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldRoomSearch.setText("ROOM SEARCH");
        jTextFieldRoomSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldRoomSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRoomSearchKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Room Controller");

        javax.swing.GroupLayout jPanelRoomLayout = new javax.swing.GroupLayout(jPanelRoom);
        jPanelRoom.setLayout(jPanelRoomLayout);
        jPanelRoomLayout.setHorizontalGroup(
            jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRoomLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRoomLayout.createSequentialGroup()
                        .addComponent(jButtonRoomRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonRoomEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButtonRoomCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRoomLayout.createSequentialGroup()
                        .addGroup(jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldRoomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
            .addGroup(jPanelRoomLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRoomLayout.setVerticalGroup(
            jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldRoomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRoomEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRoomCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRoomRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanelRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 820, 450));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 810, 450));

        jPanel1.setBackground(new java.awt.Color(3, 185, 253));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Hotel Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 810, 90));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomActionPerformed
        // TODO add your handling code here:
        jPanelRoom.setVisible(true);
        jPanelBooking.setVisible(false);
        jPanelCustomer.setVisible(false);
        jPanelWorker.setVisible(false);
    }//GEN-LAST:event_jButtonRoomActionPerformed

    private void jButtonBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookingActionPerformed
        // TODO add your handling code here:
        setBookingTable();
        jPanelRoom.setVisible(false);
        jPanelBooking.setVisible(true);
        jPanelCustomer.setVisible(false);
        jPanelWorker.setVisible(false);
    }//GEN-LAST:event_jButtonBookingActionPerformed

    private void jButtonRoomRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomRemoveActionPerformed
        Integer id = (Integer) jTableRoom.getValueAt(jTableRoom.getSelectedRow(), 0);
        boolean result = roomDAO.removeRoomRow(id);
        if (result) {
            JOptionPane.showMessageDialog(this, "Success Remove", "Remove", JOptionPane.INFORMATION_MESSAGE);
            setRoomTable();
        }else{
            JOptionPane.showMessageDialog(this, "Room data silinmedi", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonRoomRemoveActionPerformed

    private void jButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerActionPerformed
        // TODO add your handling code here:
        setCustomerTable();
        jPanelRoom.setVisible(false);
        jPanelBooking.setVisible(false);
        jPanelCustomer.setVisible(true);
        jPanelWorker.setVisible(false);
    }//GEN-LAST:event_jButtonCustomerActionPerformed

    private void jButtonWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerActionPerformed
        // TODO add your handling code here:
        setWorkerTable();
        jPanelRoom.setVisible(false);
        jPanelBooking.setVisible(false);
        jPanelCustomer.setVisible(false);
        jPanelWorker.setVisible(true);
    }//GEN-LAST:event_jButtonWorkerActionPerformed

    private void jTextFieldRoomSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRoomSearchKeyReleased
        //String search = jTextFieldRoomSearch.getText();
        //setRoomTable();
        //dinamikSearch(search);
        
    }//GEN-LAST:event_jTextFieldRoomSearchKeyReleased

    private void jButtonWorkerRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerRemoveActionPerformed
        Integer id = (Integer) jTableWorker.getValueAt(jTableWorker.getSelectedRow(), 0);
        boolean result = workerDAO.removeWorkerTableRow(id);
        if (result) {
            setWorkerTable();
        }else{
            JOptionPane.showMessageDialog(this, "Worker data silinmedi", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonWorkerRemoveActionPerformed

    private void jTextFieldFilterCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilterCustomerKeyReleased
        String filter = jTextFieldFilterCustomer.getText().toLowerCase();
        filterCustomer(filter);
    }//GEN-LAST:event_jTextFieldFilterCustomerKeyReleased

    private void jButtonCustomerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerCreateActionPerformed
        JFrameCustomerEditAndCreate create = new JFrameCustomerEditAndCreate();
        create.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCustomerCreateActionPerformed

    private void jButtonCustomerEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerEditActionPerformed
       Integer id = (Integer) jTableCustomer.getValueAt(jTableCustomer.getSelectedRow(), 0);
       List<Customer> list = customerDAO.getAllCustomer();
       for(Customer item : list){
           if (item.getId() == id) {
                JFrameCustomerEditAndCreate c = new JFrameCustomerEditAndCreate(item.getName(),
                        item.getSurname(), item.getEmail(), item.getGender(), item.getNationality(),
                        item.getPhone(), item.getAddress(), item.getDate().toString());
                c.setVisible(true);
                this.setVisible(false);
           }
       }
       //System.out.println(id);
    }//GEN-LAST:event_jButtonCustomerEditActionPerformed

    private void jButtonWorkerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerCreateActionPerformed
        JFrameWorkerEditAndCreate w = new JFrameWorkerEditAndCreate();
        w.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonWorkerCreateActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdminController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButtonBooking;
    private javax.swing.JButton jButtonBookingCreate;
    private javax.swing.JButton jButtonBookingEdit;
    private javax.swing.JButton jButtonBookingRemove;
    private javax.swing.JButton jButtonCustomer;
    private javax.swing.JButton jButtonCustomerCreate;
    private javax.swing.JButton jButtonCustomerEdit;
    private javax.swing.JButton jButtonCustomerRemove;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRoom;
    private javax.swing.JButton jButtonRoomCreate;
    private javax.swing.JButton jButtonRoomEdit;
    private javax.swing.JButton jButtonRoomRemove;
    private javax.swing.JButton jButtonWorker;
    private javax.swing.JButton jButtonWorkerCreate;
    private javax.swing.JButton jButtonWorkerEdit;
    private javax.swing.JButton jButtonWorkerRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBooking;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelRoom;
    private javax.swing.JPanel jPanelWorker;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableBooking;
    private javax.swing.JTable jTableCustomer;
    private javax.swing.JTable jTableRoom;
    private javax.swing.JTable jTableWorker;
    private javax.swing.JTextField jTextFieldBookingSearch;
    private javax.swing.JTextField jTextFieldFilterCustomer;
    private javax.swing.JTextField jTextFieldRoomSearch;
    private javax.swing.JTextField jTextFieldWorkerSearch;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables

    private void getPanelRoom() {
        jPanelRoom.setVisible(true);
        jPanelBooking.setVisible(false);
        jPanelCustomer.setVisible(false);
        jPanelWorker.setVisible(false);
    }

    private void setRoomTable() {
        
        List<Room> rooms = roomDAO.getAllRoom();
        
        DefaultTableModel dtm = new DefaultTableModel();
        
        dtm.addColumn("ID");
        dtm.addColumn("Property");
        dtm.addColumn("Type");
        dtm.addColumn("View");
        dtm.addColumn("Adult no");
        dtm.addColumn("Child no");
        dtm.addColumn("Number");
        dtm.addColumn("Status");
        
        for(Room item : rooms){
            dtm.addRow(new Object[]{item.getId(), item.getProperty(), item.getType(), item.getView(), 
            item.getAdultNo(), item.getChildNo(), item.getNumber(), item.isStatus()});
        }
        
        jTableRoom.setModel(dtm);
    }
    
    private void setBookingTable(){
        List<Booking> bookings = bookingDAO.getAllBoking();
        
        DefaultTableModel dtmBooking = new DefaultTableModel();
        
        dtmBooking.addColumn("ID");
        dtmBooking.addColumn("Check In");
        dtmBooking.addColumn("Check Out");
        dtmBooking.addColumn("Room Property");
        dtmBooking.addColumn("Room Type");
        dtmBooking.addColumn("Room Number");
        dtmBooking.addColumn("Customer Name");
        dtmBooking.addColumn("Customer Surname");
        
        for(Booking item : bookings){
            dtmBooking.addRow(new Object[]{item.getId(), item.getCheckIN(), item.getCheckOUT(),
                    item.getRoom().getProperty(), item.getRoom().getType(), item.getRoom().getNumber(),
                    item.getCustomer().getName(), item.getCustomer().getSurname()});
            System.out.println(item);
        }
        
        jTableBooking.setModel(dtmBooking);
    
    }

    private void setWorkerTable() {

        List<Worker> workers = workerDAO.getAllWorker();
        
        DefaultTableModel dtm = new DefaultTableModel();
        
        dtm.addColumn("ID");
        dtm.addColumn("Name");
        dtm.addColumn("Surname");
        dtm.addColumn("Gender");
        dtm.addColumn("Date Of Birth");
        dtm.addColumn("E-Mail");
        dtm.addColumn("Phone");
        dtm.addColumn("Address");
        dtm.addColumn("Salary");
        dtm.addColumn("Username");
        dtm.addColumn("Password");
        
        for(Worker item : workers){
            dtm.addRow(new Object[]{item.getId(), item.getName(), item.getSurname(),
                    item.getGender(), item.getDate(), item.getEmail(), item.getPhone(),
                    item.getAddress(), item.getSalary(),
                    item.getUsername(), item.getPassword()});
            //System.out.println(item);
        }
        
        jTableWorker.setModel(dtm);

    }

    private void setCustomerTable() {

        List<Customer> customers = customerDAO.getAllCustomer();
        
        dtmCustom = new DefaultTableModel();
        
        dtmCustom.addColumn("ID");
        dtmCustom.addColumn("Name");
        dtmCustom.addColumn("Surname");
        dtmCustom.addColumn("Date of Birth");
        dtmCustom.addColumn("Gender");
        dtmCustom.addColumn("Address");
        dtmCustom.addColumn("Phone");
        dtmCustom.addColumn("E-Mail");
        dtmCustom.addColumn("Nationality");
        
        for(Customer item : customers){
            dtmCustom.addRow(new Object[]{item.getId(), item.getName(), item.getSurname(), 
                        item.getDate(), item.getGender(), item.getAddress(),
                        item.getPhone(), item.getEmail(), item.getNationality()});
        }
        
        jTableCustomer.setModel(dtmCustom);
    }
    
    public void filterCustomer(String filter){
       TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(dtmCustom);
       
       jTableCustomer.setRowSorter(trs);
       
       trs.setRowFilter(RowFilter.regexFilter(filter)); 
       
    }

    private void selectRoomTableRow() {
       jTableRoom.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
           @Override
           public void valueChanged(ListSelectionEvent lse) {
               jButtonRoomRemove.setEnabled(true);
               jButtonRoomEdit.setEnabled(true);
           }
       });
    }

    private void selectBookingTableRow() {
        jTableBooking.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                jButtonBookingEdit.setEnabled(true);
                jButtonBookingRemove.setEnabled(true);
            }
        });
    }

    private void selectWorkerTableRow() {
        jTableWorker.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                jButtonWorkerEdit.setEnabled(true);
                jButtonWorkerRemove.setEnabled(true);
            }
        });
    }

    private void selectCustomerTableRow() {
        jTableCustomer.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                jButtonCustomerEdit.setEnabled(true);
                jButtonCustomerRemove.setEnabled(true);
            }
        }); 
    }

    private void buttonEnable() {
        jButtonRoomRemove.setEnabled(false);
        jButtonRoomEdit.setEnabled(false);
        jButtonBookingEdit.setEnabled(false);
        jButtonBookingRemove.setEnabled(false);
        jButtonWorkerEdit.setEnabled(false);
        jButtonWorkerRemove.setEnabled(false);
        jButtonCustomerEdit.setEnabled(false);
        jButtonCustomerRemove.setEnabled(false);
    }
}
